version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - redis-data:/data

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
